// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EntryInfo is one entry as surfaced to the credential picker: enough to
 * display and reference it, never the secret. UUID is the base64 string the
 * credential reference stores.
 */
export class EntryInfo {
    /**
     * Creates a new EntryInfo instance.
     * @param {Partial<EntryInfo>} [$$source = {}] - The source object to create the EntryInfo.
     */
    constructor($$source = {}) {
        if (!("uuid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uuid"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("has_pass" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_pass"] = false;
        }
        if (!("attachments" in $$source)) {
            /**
             * attachment keys, for key-file auth
             * @member
             * @type {string[]}
             */
            this["attachments"] = [];
        }
        if (!("custom_keys" in $$source)) {
            /**
             * non-standard String keys
             * @member
             * @type {string[]}
             */
            this["custom_keys"] = [];
        }
        if (!("group_path" in $$source)) {
            /**
             * "Root/Servers/prod" for display
             * @member
             * @type {string}
             */
            this["group_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EntryInfo}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField4_0($$parsedSource["attachments"]);
        }
        if ("custom_keys" in $$parsedSource) {
            $$parsedSource["custom_keys"] = $$createField5_0($$parsedSource["custom_keys"]);
        }
        return new EntryInfo(/** @type {Partial<EntryInfo>} */($$parsedSource));
    }
}

/**
 * GroupInfo is one group node in the browse tree.
 */
export class GroupInfo {
    /**
     * Creates a new GroupInfo instance.
     * @param {Partial<GroupInfo>} [$$source = {}] - The source object to create the GroupInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {GroupInfo[]}
             */
            this["groups"] = [];
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {EntryInfo[]}
             */
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GroupInfo}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField2_0($$parsedSource["groups"]);
        }
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField3_0($$parsedSource["entries"]);
        }
        return new GroupInfo(/** @type {Partial<GroupInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = GroupInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = EntryInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
