// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

/**
 * CreateInput is a tagged union; the same shape we used in Rust IPC.
 */
export class CreateInput {
    /**
     * Creates a new CreateInput instance.
     * @param {Partial<CreateInput>} [$$source = {}] - The source object to create the CreateInput.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("folder_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["folder_id"] = null;
        }
        if (!("hint" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["hint"] = null;
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("default_username" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["default_username"] = null;
        }
        if (!("rotation_reminder_days" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["rotation_reminder_days"] = null;
        }
        if (!("expires_at" in $$source)) {
            /**
             * ExpiresAt is the token/key expiry as a unix timestamp (nil = no
             * expiry). Set by the user for time-limited secrets - API tokens,
             * setup / auth keys - so the UI can warn before they lapse.
             * @member
             * @type {number | null}
             */
            this["expires_at"] = null;
        }
        if (!("password" in $$source)) {
            /**
             * password
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("params" in $$source)) {
            /**
             * key_generate
             * @member
             * @type {GenerateParams | null}
             */
            this["params"] = null;
        }
        if (!("private_openssh" in $$source)) {
            /**
             * key_import_paste
             * @member
             * @type {string}
             */
            this["private_openssh"] = "";
        }
        if (!("passphrase" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["passphrase"] = null;
        }
        if (!("key_path" in $$source)) {
            /**
             * key_file_ref
             * @member
             * @type {string}
             */
            this["key_path"] = "";
        }
        if (!("socket_path" in $$source)) {
            /**
             * agent
             * @member
             * @type {string | null}
             */
            this["socket_path"] = null;
        }
        if (!("fingerprint" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["fingerprint"] = null;
        }
        if (!("key_basename" in $$source)) {
            /**
             * opkssh
             * @member
             * @type {string}
             */
            this["key_basename"] = "";
        }
        if (!("opkssh_config_yaml" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["opkssh_config_yaml"] = "";
        }
        if (!("provider_hint" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["provider_hint"] = null;
        }
        if (!("max_cert_age_hours" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["max_cert_age_hours"] = null;
        }
        if (!("min_remaining_before_refresh_minutes" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["min_remaining_before_refresh_minutes"] = null;
        }
        if (!("api_token_id" in $$source)) {
            /**
             * api_token
             * @member
             * @type {string}
             */
            this["api_token_id"] = "";
        }
        if (!("api_token_secret" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_token_secret"] = "";
        }
        if (!("keepass_db_id" in $$source)) {
            /**
             * keepass - a reference into a registered .kdbx. No secret is passed or
             * stored; the secret is read from KeePass at connect time.
             * @member
             * @type {string}
             */
            this["keepass_db_id"] = "";
        }
        if (!("keepass_entry_uuid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keepass_entry_uuid"] = "";
        }
        if (!("keepass_field" in $$source)) {
            /**
             * "password" | custom field | attachment key
             * @member
             * @type {string}
             */
            this["keepass_field"] = "";
        }
        if (!("keepass_is_key" in $$source)) {
            /**
             * KeepassIsKey marks the referenced field as a private key (so the resolver
             * parses it as a signer) rather than a password.
             * @member
             * @type {boolean}
             */
            this["keepass_is_key"] = false;
        }
        if (!("bitwarden_server_id" in $$source)) {
            /**
             * bitwarden - a reference into a registered Vaultwarden / Bitwarden server.
             * No secret is passed or stored; the secret is read from the server's vault
             * at connect time.
             * @member
             * @type {string}
             */
            this["bitwarden_server_id"] = "";
        }
        if (!("bitwarden_cipher_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bitwarden_cipher_id"] = "";
        }
        if (!("bitwarden_field" in $$source)) {
            /**
             * "password" | "username" | "privatekey" | custom field
             * @member
             * @type {string}
             */
            this["bitwarden_field"] = "";
        }
        if (!("bitwarden_is_key" in $$source)) {
            /**
             * BitwardenIsKey marks the referenced field as a private key.
             * @member
             * @type {boolean}
             */
            this["bitwarden_is_key"] = false;
        }
        if (!("infisical_server_id" in $$source)) {
            /**
             * infisical - a reference into a registered Infisical server. No secret is
             * passed or stored; the value is read from the server at connect time.
             * @member
             * @type {string}
             */
            this["infisical_server_id"] = "";
        }
        if (!("infisical_project_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["infisical_project_id"] = "";
        }
        if (!("infisical_environment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["infisical_environment"] = "";
        }
        if (!("infisical_secret_path" in $$source)) {
            /**
             * "" => "/"
             * @member
             * @type {string}
             */
            this["infisical_secret_path"] = "";
        }
        if (!("infisical_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["infisical_key"] = "";
        }
        if (!("infisical_is_key" in $$source)) {
            /**
             * InfisicalIsKey marks the referenced secret value as a private key.
             * @member
             * @type {boolean}
             */
            this["infisical_is_key"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateInput}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField9_0($$parsedSource["params"]);
        }
        return new CreateInput(/** @type {Partial<CreateInput>} */($$parsedSource));
    }
}

/**
 * CreateResult mirrors the Rust struct; public_key + fingerprint surfaced to
 * UI for key-generate / key-import flows.
 */
export class CreateResult {
    /**
     * Creates a new CreateResult instance.
     * @param {Partial<CreateResult>} [$$source = {}] - The source object to create the CreateResult.
     */
    constructor($$source = {}) {
        if (!("credential" in $$source)) {
            /**
             * @member
             * @type {store$0.CredentialRef | null}
             */
            this["credential"] = null;
        }
        if (!("public_key" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["public_key"] = null;
        }
        if (!("fingerprint" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["fingerprint"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("credential" in $$parsedSource) {
            $$parsedSource["credential"] = $$createField0_0($$parsedSource["credential"]);
        }
        return new CreateResult(/** @type {Partial<CreateResult>} */($$parsedSource));
    }
}

/**
 * GenerateParams collects the user-supplied options for fresh key gen.
 */
export class GenerateParams {
    /**
     * Creates a new GenerateParams instance.
     * @param {Partial<GenerateParams>} [$$source = {}] - The source object to create the GenerateParams.
     */
    constructor($$source = {}) {
        if (!("key_type" in $$source)) {
            /**
             * @member
             * @type {KeyType}
             */
            this["key_type"] = KeyType.$zero;
        }
        if (!("bits" in $$source)) {
            /**
             * RSA: 2048/3072/4096. ECDSA: 256/384/521.
             * @member
             * @type {number | null}
             */
            this["bits"] = null;
        }
        if (!("comment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }
        if (!("passphrase" in $$source)) {
            /**
             * nil => unencrypted
             * @member
             * @type {string | null}
             */
            this["passphrase"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateParams instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GenerateParams}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GenerateParams(/** @type {Partial<GenerateParams>} */($$parsedSource));
    }
}

/**
 * KeyType is the user-facing key kind.
 * @readonly
 * @enum {string}
 */
export const KeyType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    KeyEd25519: "ed25519",
    KeyRSA: "rsa",
    KeyECDSA: "ecdsa",
};

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {StatusKind}
             */
            this["state"] = StatusKind.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["auto_unlock_available"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * SidecarStrength reports how strongly an existing auto-unlock sidecar is
             * bound to this machine ("strong" | "weak" | "none"). "weak" means the v1
             * format whose key derivation can fall back to the hostname; the UI warns
             * on it. Empty when no sidecar / not applicable.
             * @member
             * @type {string | undefined}
             */
            this["sidecar_strength"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

/**
 * Status reports whether a vault file exists and whether we have it unlocked.
 * @readonly
 * @enum {string}
 */
export const StatusKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusNotInitialized: "not_initialized",
    StatusLocked: "locked",
    StatusUnlocked: "unlocked",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = GenerateParams.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = store$0.CredentialRef.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
