// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConnectionAttention is one row of "post-import the user must touch this
 * connection". Reasons we emit:
 * 
 *   "inline-username":
 *       RDM had a username typed into the entry but no credential
 *       reference. We imported the username as an override; the user
 *       must attach a credential.
 *   "external-cred-ref":
 *       RDM linked a credential by saved-path (vault somewhere), but we
 *       don't copy the actual secret - credentials are imported into
 *       our vault only on explicit user action. The connection has
 *       overrides for username/host but no usable auth_ref.
 *   "private-key-file":
 *       RDM had a PrivateKeyCertificateFileName set (key on disk). Our
 *       store has no concept of "filesystem key without a credential
 *       row"; the user has to import the key + assign it.
 */
export class ConnectionAttention {
    /**
     * Creates a new ConnectionAttention instance.
     * @param {Partial<ConnectionAttention>} [$$source = {}] - The source object to create the ConnectionAttention.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["detail"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionAttention instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionAttention}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionAttention(/** @type {Partial<ConnectionAttention>} */($$parsedSource));
    }
}

/**
 * Summary is what the IPC layer hands back to the UI after an import.
 */
export class Summary {
    /**
     * Creates a new Summary instance.
     * @param {Partial<Summary>} [$$source = {}] - The source object to create the Summary.
     */
    constructor($$source = {}) {
        if (!("folders_created" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["folders_created"] = 0;
        }
        if (!("connections_created" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["connections_created"] = 0;
        }
        if (!("images_stored" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["images_stored"] = 0;
        }
        if (!("jump_resolved" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["jump_resolved"] = 0;
        }
        if (!("jump_unresolved" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["jump_unresolved"] = 0;
        }
        if (!("skipped_non_ssh" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skipped_non_ssh"] = 0;
        }
        if (!("credentials_created" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["credentials_created"] = 0;
        }
        if (!("credentials_need_secret" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["credentials_need_secret"] = 0;
        }
        if (!("unresolved_jumps" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["unresolved_jumps"] = [];
        }
        if (!("unresolved_creds" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["unresolved_creds"] = [];
        }
        if (!("needs_attention" in $$source)) {
            /**
             * @member
             * @type {ConnectionAttention[]}
             */
            this["needs_attention"] = [];
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Summary}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType2;
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("unresolved_jumps" in $$parsedSource) {
            $$parsedSource["unresolved_jumps"] = $$createField8_0($$parsedSource["unresolved_jumps"]);
        }
        if ("unresolved_creds" in $$parsedSource) {
            $$parsedSource["unresolved_creds"] = $$createField9_0($$parsedSource["unresolved_creds"]);
        }
        if ("needs_attention" in $$parsedSource) {
            $$parsedSource["needs_attention"] = $$createField10_0($$parsedSource["needs_attention"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField11_0($$parsedSource["warnings"]);
        }
        return new Summary(/** @type {Partial<Summary>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ConnectionAttention.createFrom;
const $$createType2 = $Create.Array($$createType1);
