// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Mark is one command: Cum is the session's output byte count when Enter
 * was sent (the command line is the line the cursor is on at that point),
 * At is Unix milliseconds.
 */
export class Mark {
    /**
     * Creates a new Mark instance.
     * @param {Partial<Mark>} [$$source = {}] - The source object to create the Mark.
     */
    constructor($$source = {}) {
        if (!("cum" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cum"] = 0;
        }
        if (!("at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Mark instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Mark}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Mark(/** @type {Partial<Mark>} */($$parsedSource));
    }
}
