// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Fingerprint renders a certificate's SHA-256 (over the DER) three ways. Words
 * is the one humans compare; the others are for logs and power users.
 */
export class Fingerprint {
    /**
     * Creates a new Fingerprint instance.
     * @param {Partial<Fingerprint>} [$$source = {}] - The source object to create the Fingerprint.
     */
    constructor($$source = {}) {
        if (!("Hex" in $$source)) {
            /**
             * "a1b2c3...": full SHA-256, lowercase, colon-free
             * @member
             * @type {string}
             */
            this["Hex"] = "";
        }
        if (!("Short" in $$source)) {
            /**
             * "a1b2-c3d4-e5f6-7890": first 8 bytes, grouped
             * @member
             * @type {string}
             */
            this["Short"] = "";
        }
        if (!("Words" in $$source)) {
            /**
             * "cobalt-otter-viola-medley": 4 words from the first 4 bytes
             * @member
             * @type {string}
             */
            this["Words"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Fingerprint instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Fingerprint}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Fingerprint(/** @type {Partial<Fingerprint>} */($$parsedSource));
    }
}

export class GuestStatus {
    /**
     * Creates a new GuestStatus instance.
     * @param {Partial<GuestStatus>} [$$source = {}] - The source object to create the GuestStatus.
     */
    constructor($$source = {}) {
        if (!("remote_ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remote_ip"] = "";
        }
        if (!("joined_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["joined_at"] = 0;
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GuestStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GuestStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GuestStatus(/** @type {Partial<GuestStatus>} */($$parsedSource));
    }
}

/**
 * Interface is one bindable network interface, for the UI dropdown.
 */
export class Interface {
    /**
     * Creates a new Interface instance.
     * @param {Partial<Interface>} [$$source = {}] - The source object to create the Interface.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * "eth0", "wg0", ...
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("ip" in $$source)) {
            /**
             * "10.0.4.7"
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Interface instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Interface}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Interface(/** @type {Partial<Interface>} */($$parsedSource));
    }
}

/**
 * ShareStatus / GuestStatus are IPC-friendly snapshots.
 */
export class ShareStatus {
    /**
     * Creates a new ShareStatus instance.
     * @param {Partial<ShareStatus>} [$$source = {}] - The source object to create the ShareStatus.
     */
    constructor($$source = {}) {
        if (!("share_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["share_id"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("bind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bind"] = "";
        }
        if (!("guests" in $$source)) {
            /**
             * @member
             * @type {GuestStatus[]}
             */
            this["guests"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShareStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShareStatus}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("guests" in $$parsedSource) {
            $$parsedSource["guests"] = $$createField3_0($$parsedSource["guests"]);
        }
        return new ShareStatus(/** @type {Partial<ShareStatus>} */($$parsedSource));
    }
}

/**
 * StartResult is returned to the App / UI.
 */
export class StartResult {
    /**
     * Creates a new StartResult instance.
     * @param {Partial<StartResult>} [$$source = {}] - The source object to create the StartResult.
     */
    constructor($$source = {}) {
        if (!("share_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["share_id"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("bind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bind"] = "";
        }
        if (!("fingerprint" in $$source)) {
            /**
             * @member
             * @type {Fingerprint}
             */
            this["fingerprint"] = (new Fingerprint());
        }
        if (!("regenerated" in $$source)) {
            /**
             * cert fingerprint changed
             * @member
             * @type {boolean}
             */
            this["regenerated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StartResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fingerprint" in $$parsedSource) {
            $$parsedSource["fingerprint"] = $$createField3_0($$parsedSource["fingerprint"]);
        }
        return new StartResult(/** @type {Partial<StartResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = GuestStatus.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Fingerprint.createFrom;
