// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Header {
    /**
     * Creates a new Header instance.
     * @param {Partial<Header>} [$$source = {}] - The source object to create the Header.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Header instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Header}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Header(/** @type {Partial<Header>} */($$parsedSource));
    }
}

export class Request {
    /**
     * Creates a new Request instance.
     * @param {Partial<Request>} [$$source = {}] - The source object to create the Request.
     */
    constructor($$source = {}) {
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {Header[]}
             */
            this["headers"] = [];
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("tls_skip_verify" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["tls_skip_verify"] = false;
        }
        if (!("socks_addr" in $$source)) {
            /**
             * SocksAddr routes the request through this SOCKS5 proxy (host:port).
             * Empty = direct.
             * @member
             * @type {string}
             */
            this["socks_addr"] = "";
        }
        if (!("timeout_seconds" in $$source)) {
            /**
             * TimeoutSeconds defaults to 60 if 0.
             * @member
             * @type {number}
             */
            this["timeout_seconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Request instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Request}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField2_0($$parsedSource["headers"]);
        }
        return new Request(/** @type {Partial<Request>} */($$parsedSource));
    }
}

export class Response {
    /**
     * Creates a new Response instance.
     * @param {Partial<Response>} [$$source = {}] - The source object to create the Response.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("status_code" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status_code"] = 0;
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {Header[]}
             */
            this["headers"] = [];
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("truncated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["truncated"] = false;
        }
        if (!("duration_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Response instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Response}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField2_0($$parsedSource["headers"]);
        }
        return new Response(/** @type {Partial<Response>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Header.createFrom;
const $$createType1 = $Create.Array($$createType0);
