// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EntryInfo is one selectable secret in the picker: a key at a folder path
 * inside an environment. The value is never carried here - only metadata.
 */
export class EntryInfo {
    /**
     * Creates a new EntryInfo instance.
     * @param {Partial<EntryInfo>} [$$source = {}] - The source object to create the EntryInfo.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * absolute Infisical folder path, e.g. "/cloudflare"
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("has_value" in $$source)) {
            /**
             * false when the value came back empty
             * @member
             * @type {boolean}
             */
            this["has_value"] = false;
        }
        if (!("comment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }
        if (!("is_key" in $$source)) {
            /**
             * IsKey is a heuristic: the value looks like a PEM private key, so the
             * picker can suggest wiring it as an SSH key rather than a password.
             * @member
             * @type {boolean}
             */
            this["is_key"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EntryInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EntryInfo(/** @type {Partial<EntryInfo>} */($$parsedSource));
    }
}

/**
 * EnvInfo is one environment (dev / prod ...) with its secrets, grouped by path.
 */
export class EnvInfo {
    /**
     * Creates a new EnvInfo instance.
     * @param {Partial<EnvInfo>} [$$source = {}] - The source object to create the EnvInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("slug" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["slug"] = "";
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {EntryInfo[]}
             */
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvInfo}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField2_0($$parsedSource["entries"]);
        }
        return new EnvInfo(/** @type {Partial<EnvInfo>} */($$parsedSource));
    }
}

/**
 * GroupInfo is a browse node: one project (workspace) holding its environments.
 * The picker renders Project -> Environment -> (path-prefixed) key.
 */
export class GroupInfo {
    /**
     * Creates a new GroupInfo instance.
     * @param {Partial<GroupInfo>} [$$source = {}] - The source object to create the GroupInfo.
     */
    constructor($$source = {}) {
        if (!("project_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("environments" in $$source)) {
            /**
             * @member
             * @type {EnvInfo[]}
             */
            this["environments"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GroupInfo}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("environments" in $$parsedSource) {
            $$parsedSource["environments"] = $$createField2_0($$parsedSource["environments"]);
        }
        return new GroupInfo(/** @type {Partial<GroupInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = EntryInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = EnvInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
