// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Peer is one [Peer] section.
 */
export class Peer {
    /**
     * Creates a new Peer instance.
     * @param {Partial<Peer>} [$$source = {}] - The source object to create the Peer.
     */
    constructor($$source = {}) {
        if (!("public_key" in $$source)) {
            /**
             * base64
             * @member
             * @type {string}
             */
            this["public_key"] = "";
        }
        if (!("has_psk" in $$source)) {
            /**
             * remembers a PSK exists while the value lives in the vault
             * @member
             * @type {boolean}
             */
            this["has_psk"] = false;
        }
        if (!("endpoint" in $$source)) {
            /**
             * host:port
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }
        if (!("allowed_ips" in $$source)) {
            /**
             * CIDRs
             * @member
             * @type {string[]}
             */
            this["allowed_ips"] = [];
        }
        if (!("keepalive" in $$source)) {
            /**
             * seconds, 0 = off
             * @member
             * @type {number}
             */
            this["keepalive"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Peer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Peer}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowed_ips" in $$parsedSource) {
            $$parsedSource["allowed_ips"] = $$createField3_0($$parsedSource["allowed_ips"]);
        }
        return new Peer(/** @type {Partial<Peer>} */($$parsedSource));
    }
}

/**
 * Profile is a parsed wg-quick style configuration. Secrets
 * (PrivateKey, PresharedKey) are populated from the vault just
 * before a tunnel starts and never persisted in the DB - the
 * stored config JSON carries them empty.
 */
export class Profile {
    /**
     * Creates a new Profile instance.
     * @param {Partial<Profile>} [$$source = {}] - The source object to create the Profile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Connect policy: ModeAlways (default when empty) or ModeAuto.
             * @member
             * @type {string | undefined}
             */
            this["mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Paused is the per-profile kill switch: while true every
             * connection using this profile dials DIRECT (tunnel never
             * starts). For "I'm on-site, leave the network alone".
             * @member
             * @type {boolean | undefined}
             */
            this["paused"] = undefined;
        }
        if (!("addresses" in $$source)) {
            /**
             * CIDR or bare IP
             * @member
             * @type {string[]}
             */
            this["addresses"] = [];
        }
        if (!("dns" in $$source)) {
            /**
             * resolver IPs inside the tunnel
             * @member
             * @type {string[]}
             */
            this["dns"] = [];
        }
        if (!("mtu" in $$source)) {
            /**
             * 0 -> 1420
             * @member
             * @type {number}
             */
            this["mtu"] = 0;
        }
        if (!("peers" in $$source)) {
            /**
             * @member
             * @type {Peer[]}
             */
            this["peers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Profile}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("addresses" in $$parsedSource) {
            $$parsedSource["addresses"] = $$createField4_0($$parsedSource["addresses"]);
        }
        if ("dns" in $$parsedSource) {
            $$parsedSource["dns"] = $$createField5_0($$parsedSource["dns"]);
        }
        if ("peers" in $$parsedSource) {
            $$parsedSource["peers"] = $$createField7_0($$parsedSource["peers"]);
        }
        return new Profile(/** @type {Partial<Profile>} */($$parsedSource));
    }
}

/**
 * Status is a point-in-time snapshot for the UI, parsed from the
 * device's UAPI dump.
 */
export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("profile_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["profile_id"] = "";
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("started_at" in $$source)) {
            /**
             * unix seconds, 0 when not running
             * @member
             * @type {number}
             */
            this["started_at"] = 0;
        }
        if (!("last_handshake" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["last_handshake"] = 0;
        }
        if (!("rx_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rx_bytes"] = 0;
        }
        if (!("tx_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tx_bytes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * Peers is only reported by helper-backed tunnels (NetBird):
             * connected remote peer count. Always 0 for plain WireGuard.
             * @member
             * @type {number | undefined}
             */
            this["peers"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Peer.createFrom;
const $$createType2 = $Create.Array($$createType1);
