// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BatchHostResult is what the frontend renders per host.
 */
export class BatchHostResult {
    /**
     * Creates a new BatchHostResult instance.
     * @param {Partial<BatchHostResult>} [$$source = {}] - The source object to create the BatchHostResult.
     */
    constructor($$source = {}) {
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_id"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * "ok" | "error" | "skipped"
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("stdout" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stdout"] = "";
        }
        if (!("stderr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stderr"] = "";
        }
        if (!("exit_code" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["exit_code"] = 0;
        }
        if (!("duration_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_ms"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchHostResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BatchHostResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatchHostResult(/** @type {Partial<BatchHostResult>} */($$parsedSource));
    }
}

/**
 * ForwardKind tags which of the three SSH forwarding modes a Forward
 * represents.
 * @readonly
 * @enum {string}
 */
export const ForwardKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * -L  local listen -> remote dial
     */
    ForwardLocal: "local",

    /**
     * -R  remote listen -> local dial
     */
    ForwardRemote: "remote",

    /**
     * -D  local SOCKS5 listen
     */
    ForwardDynamic: "dynamic",

    /**
     * ForwardReverseProxy is the "give internet" tunnel: a remote listener
     * (like -R) whose accepted connections are serviced by an in-process HTTP
     * proxy that dials out from the ssh-tool machine's network. Lets a server
     * with no outbound net borrow the local box's connectivity via http_proxy.
     */
    ForwardReverseProxy: "reverse-proxy",
};

/**
 * ForwardState reports a forward's current lifecycle.
 * @readonly
 * @enum {string}
 */
export const ForwardState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StateStopped: "stopped",
    StateListening: "listening",
    StateError: "error",
};

/**
 * ForwardStatus is the IPC-friendly snapshot. Pool returns slices of these
 * for display in the UI.
 */
export class ForwardStatus {
    /**
     * Creates a new ForwardStatus instance.
     * @param {Partial<ForwardStatus>} [$$source = {}] - The source object to create the ForwardStatus.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {ForwardKind}
             */
            this["kind"] = ForwardKind.$zero;
        }
        if (!("session_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["session_id"] = "";
        }
        if (!("local_addr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["local_addr"] = "";
        }
        if (!("local_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["local_port"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["remote_host"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["remote_port"] = undefined;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {ForwardState}
             */
            this["state"] = ForwardState.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("bytes_in" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes_in"] = 0;
        }
        if (!("bytes_out" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes_out"] = 0;
        }
        if (!("started_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["started_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForwardStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ForwardStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForwardStatus(/** @type {Partial<ForwardStatus>} */($$parsedSource));
    }
}

/**
 * PacketDecode is the protocol-specific payload dissection. Type
 * identifies the protocol; Fields holds key/value pairs the UI
 * renders in the Decode tab; Summary is a one-line gloss for the
 * flow row ("DHCPDISCOVER for 10.0.0.5" etc.).
 */
export class PacketDecode {
    /**
     * Creates a new PacketDecode instance.
     * @param {Partial<PacketDecode>} [$$source = {}] - The source object to create the PacketDecode.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * "dhcp" | "dns" | "arp"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * one-line gloss
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("fields" in $$source)) {
            /**
             * structured key/value pairs
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["fields"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PacketDecode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PacketDecode}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField2_0($$parsedSource["fields"]);
        }
        return new PacketDecode(/** @type {Partial<PacketDecode>} */($$parsedSource));
    }
}

/**
 * ParsedPacket is the structured form of a single tcpdump line. The
 * fields are best-effort - when the parser can't infer something the
 * strings stay empty. Cum (cumulative byte count carried by the line
 * stream) lets the frontend deduplicate against late events the same
 * way Terminal.svelte does for PTY output.
 */
export class ParsedPacket {
    /**
     * Creates a new ParsedPacket instance.
     * @param {Partial<ParsedPacket>} [$$source = {}] - The source object to create the ParsedPacket.
     */
    constructor($$source = {}) {
        if (!("raw" in $$source)) {
            /**
             * original tcpdump line (header line)
             * @member
             * @type {string}
             */
            this["raw"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * "13:45:12.345678" (time only)
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("proto" in $$source)) {
            /**
             * "tcp", "udp", "icmp", "arp", "other"
             * @member
             * @type {string}
             */
            this["proto"] = "";
        }
        if (!("src_ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["src_ip"] = "";
        }
        if (!("src_port" in $$source)) {
            /**
             * 0 when n/a (ARP / ICMP / unknown)
             * @member
             * @type {number}
             */
            this["src_port"] = 0;
        }
        if (!("dst_ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dst_ip"] = "";
        }
        if (!("dst_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dst_port"] = 0;
        }
        if (!("length" in $$source)) {
            /**
             * payload length, 0 when unknown
             * @member
             * @type {number}
             */
            this["length"] = 0;
        }
        if (!("info" in $$source)) {
            /**
             * proto-specific summary (e.g. ARP request)
             * @member
             * @type {string}
             */
            this["info"] = "";
        }
        if (!("flow_key" in $$source)) {
            /**
             * FlowKey is the canonical conversation key: lexicographically
             * smaller endpoint first, plus proto. Same key for both directions
             * of a TCP conversation. Empty for non-IP packets.
             * @member
             * @type {string}
             */
            this["flow_key"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Decoded holds the structured payload-level dissection when
             * verbose mode is on and the proto is recognised (DHCP, DNS, ARP).
             * Empty Type means no decode was attempted or none matched.
             * @member
             * @type {PacketDecode | null | undefined}
             */
            this["decoded"] = undefined;
        }
        if (!("seq" in $$source)) {
            /**
             * Seq is the capture's monotonic sequence number for this packet
             * (1-based), assigned server-side as it's appended to the history
             * ring. The frontend uses it to dedupe a post-detach snapshot
             * against the live stream: a live chunk with Seq <= the snapshot's
             * cum was already in the snapshot. 0 on packets that predate the
             * stamping (e.g. pre-Session banner lines).
             * @member
             * @type {number}
             */
            this["seq"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParsedPacket instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ParsedPacket}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("decoded" in $$parsedSource) {
            $$parsedSource["decoded"] = $$createField10_0($$parsedSource["decoded"]);
        }
        return new ParsedPacket(/** @type {Partial<ParsedPacket>} */($$parsedSource));
    }
}

/**
 * RouteResult is the parsed output of `ip route get`. Dev is the egress
 * interface the kernel picked; Src is the source address it would stamp
 * on the packet; Via is the gateway (empty for on-link). Mismatch is
 * set by the caller's interpretation, not parsed here. Raw keeps the
 * full line for display.
 */
export class RouteResult {
    /**
     * Creates a new RouteResult instance.
     * @param {Partial<RouteResult>} [$$source = {}] - The source object to create the RouteResult.
     */
    constructor($$source = {}) {
        if (!("dst" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dst"] = "";
        }
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("dev" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dev"] = "";
        }
        if (!("src" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["src"] = "";
        }
        if (!("via" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["via"] = "";
        }
        if (!("raw" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["raw"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RouteResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RouteResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RouteResult(/** @type {Partial<RouteResult>} */($$parsedSource));
    }
}

/**
 * ServerStats is a one-shot snapshot of a remote host's basic health, shown
 * in the status bar for the focused session (MobaXterm-style). Every field
 * is best-effort: a host that doesn't answer a given section (network gear,
 * a stripped container, a non-Linux box) leaves that metric zeroed and OK
 * reflects whether ANY section parsed.
 */
export class ServerStats {
    /**
     * Creates a new ServerStats instance.
     * @param {Partial<ServerStats>} [$$source = {}] - The source object to create the ServerStats.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("load1" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["load1"] = 0;
        }
        if (!("load5" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["load5"] = 0;
        }
        if (!("load15" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["load15"] = 0;
        }
        if (!("mem_used_pct" in $$source)) {
            /**
             * 0..100, -1 if unknown
             * @member
             * @type {number}
             */
            this["mem_used_pct"] = 0;
        }
        if (!("disk_used_pct" in $$source)) {
            /**
             * 0..100 for /, -1 if unknown
             * @member
             * @type {number}
             */
            this["disk_used_pct"] = 0;
        }
        if (!("users" in $$source)) {
            /**
             * logged-in users, -1 if unknown
             * @member
             * @type {number}
             */
            this["users"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerStats(/** @type {Partial<ServerStats>} */($$parsedSource));
    }
}

/**
 * SftpEntry is the wire format we hand back to the frontend. Mirrors
 * sftp.FileInfo just enough to render a row.
 */
export class SftpEntry {
    /**
     * Creates a new SftpEntry instance.
     * @param {Partial<SftpEntry>} [$$source = {}] - The source object to create the SftpEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * absolute path on the remote
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("is_dir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_dir"] = false;
        }
        if (!("is_link" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_link"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("mode" in $$source)) {
            /**
             * unix-style permission bits
             * @member
             * @type {number}
             */
            this["mode"] = 0;
        }
        if (!("mode_str" in $$source)) {
            /**
             * e.g. "-rw-r--r--"
             * @member
             * @type {string}
             */
            this["mode_str"] = "";
        }
        if (!("mod_time" in $$source)) {
            /**
             * unix seconds
             * @member
             * @type {number}
             */
            this["mod_time"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * symlink target if IsLink
             * @member
             * @type {string | undefined}
             */
            this["target"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SftpEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SftpEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SftpEntry(/** @type {Partial<SftpEntry>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = PacketDecode.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
