// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BatchHostResult is what the frontend renders per host.
 */
export class BatchHostResult {
    /**
     * Creates a new BatchHostResult instance.
     * @param {Partial<BatchHostResult>} [$$source = {}] - The source object to create the BatchHostResult.
     */
    constructor($$source = {}) {
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_id"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * "ok" | "error" | "skipped"
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("stdout" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stdout"] = "";
        }
        if (!("stderr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stderr"] = "";
        }
        if (!("exit_code" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["exit_code"] = 0;
        }
        if (!("duration_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_ms"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchHostResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BatchHostResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatchHostResult(/** @type {Partial<BatchHostResult>} */($$parsedSource));
    }
}

/**
 * ContainerInfo is one running container as the picker shows it.
 */
export class ContainerInfo {
    /**
     * Creates a new ContainerInfo instance.
     * @param {Partial<ContainerInfo>} [$$source = {}] - The source object to create the ContainerInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("image" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["image"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContainerInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContainerInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContainerInfo(/** @type {Partial<ContainerInfo>} */($$parsedSource));
    }
}

/**
 * DirUsage is one directory in the "largest directories" list of a
 * filesystem, size in 1024-byte blocks.
 */
export class DirUsage {
    /**
     * Creates a new DirUsage instance.
     * @param {Partial<DirUsage>} [$$source = {}] - The source object to create the DirUsage.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("size_kb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size_kb"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirUsage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DirUsage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DirUsage(/** @type {Partial<DirUsage>} */($$parsedSource));
    }
}

/**
 * DiskPart is one real (non-pseudo) filesystem in the popup's storage list.
 * Sizes are in 1024-byte blocks (df -Pk), so the frontend can render absolute
 * used/total alongside the percentage.
 */
export class DiskPart {
    /**
     * Creates a new DiskPart instance.
     * @param {Partial<DiskPart>} [$$source = {}] - The source object to create the DiskPart.
     */
    constructor($$source = {}) {
        if (!("mount" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mount"] = "";
        }
        if (!("fs" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fs"] = "";
        }
        if (!("size_kb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size_kb"] = 0;
        }
        if (!("used_kb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["used_kb"] = 0;
        }
        if (!("avail_kb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["avail_kb"] = 0;
        }
        if (!("used_pct" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["used_pct"] = 0;
        }
        if (!("inode_pct" in $$source)) {
            /**
             * InodePct is df -Pi's IUse% for the same mount, -1 when the fs does
             * not report inodes (btrfs, vfat and friends print "-").
             * @member
             * @type {number}
             */
            this["inode_pct"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiskPart instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiskPart}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiskPart(/** @type {Partial<DiskPart>} */($$parsedSource));
    }
}

/**
 * DiskSize is one real filesystem in the facts report.
 */
export class DiskSize {
    /**
     * Creates a new DiskSize instance.
     * @param {Partial<DiskSize>} [$$source = {}] - The source object to create the DiskSize.
     */
    constructor($$source = {}) {
        if (!("mount" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mount"] = "";
        }
        if (!("size_kb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size_kb"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiskSize instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiskSize}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiskSize(/** @type {Partial<DiskSize>} */($$parsedSource));
    }
}

/**
 * DiskTopResult is what DiskTopDirs found. Partial is set when du was cut
 * off by the timeout or could not read some directories (permission), so
 * the list is a lower bound rather than the whole picture.
 */
export class DiskTopResult {
    /**
     * Creates a new DiskTopResult instance.
     * @param {Partial<DiskTopResult>} [$$source = {}] - The source object to create the DiskTopResult.
     */
    constructor($$source = {}) {
        if (!("dirs" in $$source)) {
            /**
             * @member
             * @type {DirUsage[]}
             */
            this["dirs"] = [];
        }
        if (!("partial" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["partial"] = false;
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiskTopResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiskTopResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dirs" in $$parsedSource) {
            $$parsedSource["dirs"] = $$createField0_0($$parsedSource["dirs"]);
        }
        return new DiskTopResult(/** @type {Partial<DiskTopResult>} */($$parsedSource));
    }
}

/**
 * ForwardKind tags which of the three SSH forwarding modes a Forward
 * represents.
 * @readonly
 * @enum {string}
 */
export const ForwardKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * -L  local listen -> remote dial
     */
    ForwardLocal: "local",

    /**
     * -R  remote listen -> local dial
     */
    ForwardRemote: "remote",

    /**
     * -D  local SOCKS5 listen
     */
    ForwardDynamic: "dynamic",

    /**
     * ForwardReverseProxy is the "give internet" tunnel: a remote listener
     * (like -R) whose accepted connections are serviced by an in-process HTTP
     * proxy that dials out from the ssh-tool machine's network. Lets a server
     * with no outbound net borrow the local box's connectivity via http_proxy.
     */
    ForwardReverseProxy: "reverse-proxy",
};

/**
 * ForwardState reports a forward's current lifecycle.
 * @readonly
 * @enum {string}
 */
export const ForwardState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StateStopped: "stopped",
    StateListening: "listening",
    StateError: "error",
};

/**
 * ForwardStatus is the IPC-friendly snapshot. Pool returns slices of these
 * for display in the UI.
 */
export class ForwardStatus {
    /**
     * Creates a new ForwardStatus instance.
     * @param {Partial<ForwardStatus>} [$$source = {}] - The source object to create the ForwardStatus.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {ForwardKind}
             */
            this["kind"] = ForwardKind.$zero;
        }
        if (!("session_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["session_id"] = "";
        }
        if (!("local_addr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["local_addr"] = "";
        }
        if (!("local_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["local_port"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["remote_host"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["remote_port"] = undefined;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {ForwardState}
             */
            this["state"] = ForwardState.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("bytes_in" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes_in"] = 0;
        }
        if (!("bytes_out" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes_out"] = 0;
        }
        if (!("started_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["started_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForwardStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ForwardStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForwardStatus(/** @type {Partial<ForwardStatus>} */($$parsedSource));
    }
}

/**
 * HostFacts is one row of the report. Values that do not apply stay at
 * their zero value / -1 and the frontend shows a dash.
 */
export class HostFacts {
    /**
     * Creates a new HostFacts instance.
     * @param {Partial<HostFacts>} [$$source = {}] - The source object to create the HostFacts.
     */
    constructor($$source = {}) {
        if (!("cpu_cores" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cpu_cores"] = 0;
        }
        if (!("cpu_model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cpu_model"] = "";
        }
        if (!("mem_kb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mem_kb"] = 0;
        }
        if (!("swap_kb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["swap_kb"] = 0;
        }
        if (!("disks" in $$source)) {
            /**
             * @member
             * @type {DiskSize[]}
             */
            this["disks"] = [];
        }
        if (!("virt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["virt"] = "";
        }
        if (!("os" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["os"] = "";
        }
        if (!("kernel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kernel"] = "";
        }
        if (!("uptime_sec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uptime_sec"] = 0;
        }
        if (!("timesync" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timesync"] = "";
        }
        if (!("updates" in $$source)) {
            /**
             * -1 unknown
             * @member
             * @type {number}
             */
            this["updates"] = 0;
        }
        if (!("security" in $$source)) {
            /**
             * -1 unknown
             * @member
             * @type {number}
             */
            this["security"] = 0;
        }
        if (!("reboot" in $$source)) {
            /**
             * yes | no | unknown | ""
             * @member
             * @type {string}
             */
            this["reboot"] = "";
        }
        if (!("failed" in $$source)) {
            /**
             * -1 unknown
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (!("ips" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["ips"] = [];
        }
        if (!("gateway" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gateway"] = "";
        }
        if (!("dns" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["dns"] = [];
        }
        if (!("ports" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["ports"] = [];
        }
        if (!("custom" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["custom"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostFacts instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HostFacts}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType3;
        const $$createField14_0 = $$createType4;
        const $$createField16_0 = $$createType4;
        const $$createField17_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("disks" in $$parsedSource) {
            $$parsedSource["disks"] = $$createField4_0($$parsedSource["disks"]);
        }
        if ("ips" in $$parsedSource) {
            $$parsedSource["ips"] = $$createField14_0($$parsedSource["ips"]);
        }
        if ("dns" in $$parsedSource) {
            $$parsedSource["dns"] = $$createField16_0($$parsedSource["dns"]);
        }
        if ("ports" in $$parsedSource) {
            $$parsedSource["ports"] = $$createField17_0($$parsedSource["ports"]);
        }
        return new HostFacts(/** @type {Partial<HostFacts>} */($$parsedSource));
    }
}

/**
 * LogTailLine is one streamed log line with its 1-based sequence number (the
 * ring watermark a re-attaching window dedupes against).
 */
export class LogTailLine {
    /**
     * Creates a new LogTailLine instance.
     * @param {Partial<LogTailLine>} [$$source = {}] - The source object to create the LogTailLine.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("seq" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seq"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogTailLine instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogTailLine}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogTailLine(/** @type {Partial<LogTailLine>} */($$parsedSource));
    }
}

/**
 * PacketDecode is the protocol-specific payload dissection. Type
 * identifies the protocol; Fields holds key/value pairs the UI
 * renders in the Decode tab; Summary is a one-line gloss for the
 * flow row ("DHCPDISCOVER for 10.0.0.5" etc.).
 */
export class PacketDecode {
    /**
     * Creates a new PacketDecode instance.
     * @param {Partial<PacketDecode>} [$$source = {}] - The source object to create the PacketDecode.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * "dhcp" | "dns" | "arp"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * one-line gloss
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("fields" in $$source)) {
            /**
             * structured key/value pairs
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["fields"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PacketDecode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PacketDecode}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField2_0($$parsedSource["fields"]);
        }
        return new PacketDecode(/** @type {Partial<PacketDecode>} */($$parsedSource));
    }
}

/**
 * ParsedPacket is the structured form of a single tcpdump line. The
 * fields are best-effort - when the parser can't infer something the
 * strings stay empty. Cum (cumulative byte count carried by the line
 * stream) lets the frontend deduplicate against late events the same
 * way Terminal.svelte does for PTY output.
 */
export class ParsedPacket {
    /**
     * Creates a new ParsedPacket instance.
     * @param {Partial<ParsedPacket>} [$$source = {}] - The source object to create the ParsedPacket.
     */
    constructor($$source = {}) {
        if (!("raw" in $$source)) {
            /**
             * original tcpdump line (header line)
             * @member
             * @type {string}
             */
            this["raw"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * "13:45:12.345678" (time only)
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("proto" in $$source)) {
            /**
             * "tcp", "udp", "icmp", "arp", "other"
             * @member
             * @type {string}
             */
            this["proto"] = "";
        }
        if (!("src_ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["src_ip"] = "";
        }
        if (!("src_port" in $$source)) {
            /**
             * 0 when n/a (ARP / ICMP / unknown)
             * @member
             * @type {number}
             */
            this["src_port"] = 0;
        }
        if (!("dst_ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dst_ip"] = "";
        }
        if (!("dst_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dst_port"] = 0;
        }
        if (!("length" in $$source)) {
            /**
             * payload length, 0 when unknown
             * @member
             * @type {number}
             */
            this["length"] = 0;
        }
        if (!("info" in $$source)) {
            /**
             * proto-specific summary (e.g. ARP request)
             * @member
             * @type {string}
             */
            this["info"] = "";
        }
        if (!("flow_key" in $$source)) {
            /**
             * FlowKey is the canonical conversation key: lexicographically
             * smaller endpoint first, plus proto. Same key for both directions
             * of a TCP conversation. Empty for non-IP packets.
             * @member
             * @type {string}
             */
            this["flow_key"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Decoded holds the structured payload-level dissection when
             * verbose mode is on and the proto is recognised (DHCP, DNS, ARP).
             * Empty Type means no decode was attempted or none matched.
             * @member
             * @type {PacketDecode | null | undefined}
             */
            this["decoded"] = undefined;
        }
        if (!("seq" in $$source)) {
            /**
             * Seq is the capture's monotonic sequence number for this packet
             * (1-based), assigned server-side as it's appended to the history
             * ring. The frontend uses it to dedupe a post-detach snapshot
             * against the live stream: a live chunk with Seq <= the snapshot's
             * cum was already in the snapshot. 0 on packets that predate the
             * stamping (e.g. pre-Session banner lines).
             * @member
             * @type {number}
             */
            this["seq"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParsedPacket instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ParsedPacket}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("decoded" in $$parsedSource) {
            $$parsedSource["decoded"] = $$createField10_0($$parsedSource["decoded"]);
        }
        return new ParsedPacket(/** @type {Partial<ParsedPacket>} */($$parsedSource));
    }
}

/**
 * ProcInfo is one row of the System status Processes tab.
 */
export class ProcInfo {
    /**
     * Creates a new ProcInfo instance.
     * @param {Partial<ProcInfo>} [$$source = {}] - The source object to create the ProcInfo.
     */
    constructor($$source = {}) {
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("cpu" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cpu"] = 0;
        }
        if (!("mem" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mem"] = 0;
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProcInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcInfo(/** @type {Partial<ProcInfo>} */($$parsedSource));
    }
}

/**
 * RouteResult is the parsed output of `ip route get`. Dev is the egress
 * interface the kernel picked; Src is the source address it would stamp
 * on the packet; Via is the gateway (empty for on-link). Mismatch is
 * set by the caller's interpretation, not parsed here. Raw keeps the
 * full line for display.
 */
export class RouteResult {
    /**
     * Creates a new RouteResult instance.
     * @param {Partial<RouteResult>} [$$source = {}] - The source object to create the RouteResult.
     */
    constructor($$source = {}) {
        if (!("dst" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dst"] = "";
        }
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("dev" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dev"] = "";
        }
        if (!("src" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["src"] = "";
        }
        if (!("via" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["via"] = "";
        }
        if (!("raw" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["raw"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RouteResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RouteResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RouteResult(/** @type {Partial<RouteResult>} */($$parsedSource));
    }
}

/**
 * ServerStats is a one-shot snapshot of a remote host's basic health, shown
 * in the status bar for the focused session (MobaXterm-style). Every field
 * is best-effort: a host that doesn't answer a given section (network gear,
 * a stripped container, a non-Linux box) leaves that metric zeroed and OK
 * reflects whether ANY section parsed.
 * 
 * The first block (Load/MemUsedPct/DiskUsedPct/Users) drives the compact
 * status-bar readout. The rest is the richer detail the "System status"
 * popup shows; all of it is optional and back-compatible - an older frontend
 * simply ignores the extra fields.
 */
export class ServerStats {
    /**
     * Creates a new ServerStats instance.
     * @param {Partial<ServerStats>} [$$source = {}] - The source object to create the ServerStats.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("load1" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["load1"] = 0;
        }
        if (!("load5" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["load5"] = 0;
        }
        if (!("load15" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["load15"] = 0;
        }
        if (!("mem_used_pct" in $$source)) {
            /**
             * 0..100, -1 if unknown
             * @member
             * @type {number}
             */
            this["mem_used_pct"] = 0;
        }
        if (!("disk_used_pct" in $$source)) {
            /**
             * 0..100 for /, -1 if unknown
             * @member
             * @type {number}
             */
            this["disk_used_pct"] = 0;
        }
        if (!("users" in $$source)) {
            /**
             * logged-in users, -1 if unknown
             * @member
             * @type {number}
             */
            this["users"] = 0;
        }
        if (!("hostname" in $$source)) {
            /**
             * Detail fields for the popup. Zero / empty / nil when unknown.
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("kernel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kernel"] = "";
        }
        if (!("uptime_sec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uptime_sec"] = 0;
        }
        if (!("ncpu" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ncpu"] = 0;
        }
        if (!("mem_total_kb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mem_total_kb"] = 0;
        }
        if (!("mem_avail_kb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mem_avail_kb"] = 0;
        }
        if (!("swap_total_kb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["swap_total_kb"] = 0;
        }
        if (!("swap_free_kb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["swap_free_kb"] = 0;
        }
        if (!("user_names" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["user_names"] = [];
        }
        if (!("partitions" in $$source)) {
            /**
             * @member
             * @type {DiskPart[]}
             */
            this["partitions"] = [];
        }
        if (!("cpu_pct" in $$source)) {
            /**
             * Local-shell extras. CPUPct is set where there is no load average
             * (Windows): busy share of all cores over a short sample, -1 elsewhere.
             * Shell names the local shell for the status bar ("WSL Ubuntu-24.04").
             * @member
             * @type {number}
             */
            this["cpu_pct"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["shell"] = undefined;
        }
        if (!("failed_units" in $$source)) {
            /**
             * FailedUnits counts failed systemd units, -1 where there is no
             * systemctl. Drives the status bar's "N failed" chip.
             * @member
             * @type {number}
             */
            this["failed_units"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerStats}
     */
    static createFrom($$source = {}) {
        const $$createField15_0 = $$createType4;
        const $$createField16_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("user_names" in $$parsedSource) {
            $$parsedSource["user_names"] = $$createField15_0($$parsedSource["user_names"]);
        }
        if ("partitions" in $$parsedSource) {
            $$parsedSource["partitions"] = $$createField16_0($$parsedSource["partitions"]);
        }
        return new ServerStats(/** @type {Partial<ServerStats>} */($$parsedSource));
    }
}

/**
 * SftpEntry is the wire format we hand back to the frontend. Mirrors
 * sftp.FileInfo just enough to render a row.
 */
export class SftpEntry {
    /**
     * Creates a new SftpEntry instance.
     * @param {Partial<SftpEntry>} [$$source = {}] - The source object to create the SftpEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * absolute path on the remote
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("is_dir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_dir"] = false;
        }
        if (!("is_link" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_link"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("mode" in $$source)) {
            /**
             * unix-style permission bits
             * @member
             * @type {number}
             */
            this["mode"] = 0;
        }
        if (!("mode_str" in $$source)) {
            /**
             * e.g. "-rw-r--r--"
             * @member
             * @type {string}
             */
            this["mode_str"] = "";
        }
        if (!("mod_time" in $$source)) {
            /**
             * unix seconds
             * @member
             * @type {number}
             */
            this["mod_time"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * symlink target if IsLink
             * @member
             * @type {string | undefined}
             */
            this["target"] = undefined;
        }
        if (!("uid" in $$source)) {
            /**
             * UID/GID come from the raw SFTP attrs. Protocol v3 carries numbers
             * only - there is no name lookup over SFTP - so the UI shows the ids.
             * -1 means the server did not report them (some non-POSIX servers).
             * @member
             * @type {number}
             */
            this["uid"] = 0;
        }
        if (!("gid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["gid"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * Owner/Group are resolved from the host's /etc/passwd and /etc/group
             * (see idnames.go) and are empty when the id is not in those files -
             * LDAP/SSSD accounts, or a server that refuses to serve them.
             * @member
             * @type {string | undefined}
             */
            this["owner"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["group"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SftpEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SftpEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SftpEntry(/** @type {Partial<SftpEntry>} */($$parsedSource));
    }
}

/**
 * UnitInfo is one systemd service in the Services tab.
 */
export class UnitInfo {
    /**
     * Creates a new UnitInfo instance.
     * @param {Partial<UnitInfo>} [$$source = {}] - The source object to create the UnitInfo.
     */
    constructor($$source = {}) {
        if (!("unit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["unit"] = "";
        }
        if (!("load" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["load"] = "";
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["active"] = "";
        }
        if (!("sub" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sub"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnitInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UnitInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UnitInfo(/** @type {Partial<UnitInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = DirUsage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = DiskSize.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
const $$createType7 = PacketDecode.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = DiskPart.createFrom;
const $$createType10 = $Create.Array($$createType9);
