// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DownloadResult is returned to the IPC layer after the staged binary
 * is written. The caller can show the byte size + hash and offer the
 * user a "Restart and update" button which calls Apply.
 */
export class DownloadResult {
    /**
     * Creates a new DownloadResult instance.
     * @param {Partial<DownloadResult>} [$$source = {}] - The source object to create the DownloadResult.
     */
    constructor($$source = {}) {
        if (!("staged_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["staged_path"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }
        if (!("verified" in $$source)) {
            /**
             * sha256 matched the manifest value
             * @member
             * @type {boolean}
             */
            this["verified"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * populated on Windows
             * @member
             * @type {string | undefined}
             */
            this["apply_script"] = undefined;
        }
        if (!("needs_restart" in $$source)) {
            /**
             * true → caller should exit after Apply
             * @member
             * @type {boolean}
             */
            this["needs_restart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadResult(/** @type {Partial<DownloadResult>} */($$parsedSource));
    }
}
