// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ImportSummary lists what the apply did (or would do, in dry-run).
 */
export class ImportSummary {
    /**
     * Creates a new ImportSummary instance.
     * @param {Partial<ImportSummary>} [$$source = {}] - The source object to create the ImportSummary.
     */
    constructor($$source = {}) {
        if (!("folders_created" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["folders_created"] = [];
        }
        if (!("folders_updated" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["folders_updated"] = [];
        }
        if (!("folders_skipped" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["folders_skipped"] = [];
        }
        if (!("conns_created" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["conns_created"] = [];
        }
        if (!("conns_updated" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["conns_updated"] = [];
        }
        if (!("conns_skipped" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["conns_skipped"] = [];
        }
        if (!("creds_created" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["creds_created"] = [];
        }
        if (!("creds_skipped" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["creds_skipped"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["cred_folders_created"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["cred_folders_skipped"] = undefined;
        }
        if (!("secrets_imported" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["secrets_imported"] = 0;
        }
        if (!("images_imported" in $$source)) {
            /**
             * ImagesImported counts custom icon blobs landed (or matched to
             * an existing content-addressed row).
             * @member
             * @type {number}
             */
            this["images_imported"] = 0;
        }
        if (!("conn_passwords_imported" in $$source)) {
            /**
             * ConnPasswordsImported counts restored per-connection password
             * overrides (password stored on the connection row itself, no
             * credential entry involved).
             * @member
             * @type {number}
             */
            this["conn_passwords_imported"] = 0;
        }
        if (!("forwards_created" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["forwards_created"] = 0;
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportSummary}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        const $$createField14_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("folders_created" in $$parsedSource) {
            $$parsedSource["folders_created"] = $$createField0_0($$parsedSource["folders_created"]);
        }
        if ("folders_updated" in $$parsedSource) {
            $$parsedSource["folders_updated"] = $$createField1_0($$parsedSource["folders_updated"]);
        }
        if ("folders_skipped" in $$parsedSource) {
            $$parsedSource["folders_skipped"] = $$createField2_0($$parsedSource["folders_skipped"]);
        }
        if ("conns_created" in $$parsedSource) {
            $$parsedSource["conns_created"] = $$createField3_0($$parsedSource["conns_created"]);
        }
        if ("conns_updated" in $$parsedSource) {
            $$parsedSource["conns_updated"] = $$createField4_0($$parsedSource["conns_updated"]);
        }
        if ("conns_skipped" in $$parsedSource) {
            $$parsedSource["conns_skipped"] = $$createField5_0($$parsedSource["conns_skipped"]);
        }
        if ("creds_created" in $$parsedSource) {
            $$parsedSource["creds_created"] = $$createField6_0($$parsedSource["creds_created"]);
        }
        if ("creds_skipped" in $$parsedSource) {
            $$parsedSource["creds_skipped"] = $$createField7_0($$parsedSource["creds_skipped"]);
        }
        if ("cred_folders_created" in $$parsedSource) {
            $$parsedSource["cred_folders_created"] = $$createField8_0($$parsedSource["cred_folders_created"]);
        }
        if ("cred_folders_skipped" in $$parsedSource) {
            $$parsedSource["cred_folders_skipped"] = $$createField9_0($$parsedSource["cred_folders_skipped"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField14_0($$parsedSource["warnings"]);
        }
        return new ImportSummary(/** @type {Partial<ImportSummary>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
