// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Summary mirrors the other importers' shape.
 */
export class Summary {
    /**
     * Creates a new Summary instance.
     * @param {Partial<Summary>} [$$source = {}] - The source object to create the Summary.
     */
    constructor($$source = {}) {
        if (!("connections_created" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["connections_created"] = 0;
        }
        if (!("connections_skipped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["connections_skipped"] = 0;
        }
        if (!("skipped_non_ssh" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skipped_non_ssh"] = 0;
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Summary}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField3_0($$parsedSource["warnings"]);
        }
        return new Summary(/** @type {Partial<Summary>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
