// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CipherInfo describes one item for the picker (decrypted metadata only, never
 * the secret itself).
 */
export class CipherInfo {
    /**
     * Creates a new CipherInfo instance.
     * @param {Partial<CipherInfo>} [$$source = {}] - The source object to create the CipherInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["type"] = 0;
        }
        if (!("is_ssh_key" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_ssh_key"] = false;
        }
        if (!("has_password" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_password"] = false;
        }
        if (!("has_totp" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_totp"] = false;
        }
        if (!("custom_keys" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["custom_keys"] = [];
        }
        if (!("attachments" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["attachments"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CipherInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CipherInfo}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("custom_keys" in $$parsedSource) {
            $$parsedSource["custom_keys"] = $$createField7_0($$parsedSource["custom_keys"]);
        }
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField8_0($$parsedSource["attachments"]);
        }
        return new CipherInfo(/** @type {Partial<CipherInfo>} */($$parsedSource));
    }
}

/**
 * CollectionInfo groups ciphers within an organization.
 */
export class CollectionInfo {
    /**
     * Creates a new CollectionInfo instance.
     * @param {Partial<CollectionInfo>} [$$source = {}] - The source object to create the CollectionInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("ciphers" in $$source)) {
            /**
             * @member
             * @type {CipherInfo[]}
             */
            this["ciphers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CollectionInfo}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ciphers" in $$parsedSource) {
            $$parsedSource["ciphers"] = $$createField2_0($$parsedSource["ciphers"]);
        }
        return new CollectionInfo(/** @type {Partial<CollectionInfo>} */($$parsedSource));
    }
}

/**
 * GroupInfo is a browse node: an organization (or the personal vault) holding
 * collections, each holding ciphers. Personal items have OrgID "".
 */
export class GroupInfo {
    /**
     * Creates a new GroupInfo instance.
     * @param {Partial<GroupInfo>} [$$source = {}] - The source object to create the GroupInfo.
     */
    constructor($$source = {}) {
        if (!("org_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["org_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("collections" in $$source)) {
            /**
             * @member
             * @type {CollectionInfo[]}
             */
            this["collections"] = [];
        }
        if (!("ciphers" in $$source)) {
            /**
             * items with no collection (personal, or org-uncollected)
             * @member
             * @type {CipherInfo[]}
             */
            this["ciphers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GroupInfo}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("collections" in $$parsedSource) {
            $$parsedSource["collections"] = $$createField2_0($$parsedSource["collections"]);
        }
        if ("ciphers" in $$parsedSource) {
            $$parsedSource["ciphers"] = $$createField3_0($$parsedSource["ciphers"]);
        }
        return new GroupInfo(/** @type {Partial<GroupInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = CipherInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = CollectionInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
