// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Info describes a backup file on disk without decrypting it.
 */
export class Info {
    /**
     * Creates a new Info instance.
     * @param {Partial<Info>} [$$source = {}] - The source object to create the Info.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Info}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info(/** @type {Partial<Info>} */($$parsedSource));
    }
}
