// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PullResult reports what was staged.
 */
export class PullResult {
    /**
     * Creates a new PullResult instance.
     * @param {Partial<PullResult>} [$$source = {}] - The source object to create the PullResult.
     */
    constructor($$source = {}) {
        if (!("generation" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["generation"] = 0;
        }
        if (!("device" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["device"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PullResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PullResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PullResult(/** @type {Partial<PullResult>} */($$parsedSource));
    }
}

/**
 * PushResult reports what landed.
 */
export class PushResult {
    /**
     * Creates a new PushResult instance.
     * @param {Partial<PushResult>} [$$source = {}] - The source object to create the PushResult.
     */
    constructor($$source = {}) {
        if (!("generation" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["generation"] = 0;
        }
        if (!("snapshot_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["snapshot_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PushResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PushResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PushResult(/** @type {Partial<PushResult>} */($$parsedSource));
    }
}
