// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {store} from '../models';
import {creds} from '../models';
import {ssh} from '../models';
import {rdm} from '../models';

export function ClearConnectionPassword(arg1:string):Promise<void>;

export function ConnectionCopyInfo(arg1:string):Promise<main.ConnectionCopyInfo>;

export function ConnectionRevealPassword(arg1:string):Promise<string>;

export function ConnectionsBatchUpdate(arg1:main.ConnectionsBatchUpdateInput):Promise<main.ConnectionsBatchUpdateResult>;

export function ConnectionsCreate(arg1:main.ConnectionsCreateInput):Promise<store.Connection>;

export function ConnectionsDelete(arg1:string):Promise<void>;

export function ConnectionsGet(arg1:string):Promise<store.Connection>;

export function ConnectionsList(arg1:any):Promise<Array<store.Connection>>;

export function ConnectionsResolve(arg1:string):Promise<store.ResolvedSettings>;

export function ConnectionsTouch(arg1:string):Promise<void>;

export function ConnectionsUpdate(arg1:main.ConnectionsUpdateInput):Promise<store.Connection>;

export function CredentialFoldersCreate(arg1:string,arg2:any):Promise<store.CredentialFolder>;

export function CredentialFoldersDelete(arg1:string):Promise<void>;

export function CredentialFoldersList():Promise<Array<store.CredentialFolder>>;

export function CredentialFoldersUpdate(arg1:string,arg2:any,arg3:any,arg4:boolean):Promise<store.CredentialFolder>;

export function CredentialsCreate(arg1:creds.CreateInput):Promise<creds.CreateResult>;

export function CredentialsDelete(arg1:string):Promise<void>;

export function CredentialsGet(arg1:string):Promise<store.CredentialRef>;

export function CredentialsHistory(arg1:string):Promise<Array<store.CredentialHistoryEntry>>;

export function CredentialsList():Promise<Array<store.CredentialRef>>;

export function CredentialsRevealSecret(arg1:string):Promise<string>;

export function CredentialsRotateKey(arg1:main.CredentialsRotateKeyInput):Promise<store.CredentialRef>;

export function CredentialsRotatePassword(arg1:string,arg2:string):Promise<store.CredentialRef>;

export function CredentialsUpdate(arg1:main.CredentialsUpdateInput):Promise<store.CredentialRef>;

export function CredentialsUsage(arg1:string):Promise<Array<store.UsageRef>>;

export function FoldersCreate(arg1:main.FoldersCreateInput):Promise<store.Folder>;

export function FoldersDelete(arg1:string):Promise<void>;

export function FoldersGet(arg1:string):Promise<store.Folder>;

export function FoldersList():Promise<Array<store.Folder>>;

export function FoldersUpdate(arg1:main.FoldersUpdateInput):Promise<store.Folder>;

export function ForwardsActive(arg1:string):Promise<Array<ssh.ForwardStatus>>;

export function ForwardsCreate(arg1:main.ForwardCreateInput):Promise<store.PortForward>;

export function ForwardsDelete(arg1:string):Promise<void>;

export function ForwardsList(arg1:string):Promise<Array<store.PortForward>>;

export function ForwardsStart(arg1:string,arg2:string):Promise<ssh.ForwardStatus>;

export function ForwardsStop(arg1:string):Promise<void>;

export function ForwardsUpdate(arg1:main.ForwardUpdateInput):Promise<store.PortForward>;

export function GetConnectionHasPassword(arg1:string):Promise<boolean>;

export function ImagesGet(arg1:string):Promise<main.ImagePayload>;

export function OpenURL(arg1:string):Promise<void>;

export function Ping(arg1:string):Promise<string>;

export function RdmImport(arg1:string,arg2:string):Promise<rdm.Summary>;

export function SetConnectionPassword(arg1:string,arg2:string):Promise<void>;

export function SettingsDelete(arg1:string):Promise<void>;

export function SettingsGet(arg1:string):Promise<string>;

export function SettingsSet(arg1:string,arg2:string):Promise<void>;

export function SftpCancelTransfer(arg1:string):Promise<void>;

export function SftpList(arg1:string,arg2:string):Promise<main.SftpListResult>;

export function SftpMkdir(arg1:string,arg2:string):Promise<void>;

export function SftpPickDownloadDest(arg1:string):Promise<string>;

export function SftpPickUploadSource():Promise<string>;

export function SftpReadPreview(arg1:string,arg2:string,arg3:number):Promise<main.SftpPreview>;

export function SftpRemove(arg1:string,arg2:string):Promise<void>;

export function SftpRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpStartDownload(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SftpStartUpload(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SftpStat(arg1:string,arg2:string):Promise<ssh.SftpEntry>;

export function SshActiveSessions():Promise<Array<main.ActiveSessionInfo>>;

export function SshCancelReconnect(arg1:string):Promise<void>;

export function SshConnect(arg1:string):Promise<main.SshConnectResult>;

export function SshDisconnect(arg1:string):Promise<void>;

export function SshLaunchBrowser(arg1:string,arg2:string):Promise<main.BrowserLaunchResult>;

export function SshResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SshRespondHostKey(arg1:string,arg2:boolean,arg3:boolean,arg4:string,arg5:number,arg6:string,arg7:string,arg8:string):Promise<void>;

export function SshSystemCommand(arg1:string):Promise<string>;

export function SshWrite(arg1:string,arg2:string):Promise<void>;

export function VaultAutoUnlock():Promise<boolean>;

export function VaultInit(arg1:string,arg2:boolean):Promise<void>;

export function VaultLock(arg1:boolean):Promise<void>;

export function VaultStatus():Promise<creds.Status>;

export function VaultUnlock(arg1:string,arg2:boolean):Promise<void>;
