// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearConnectionPassword(arg1) {
  return window['go']['main']['App']['ClearConnectionPassword'](arg1);
}

export function ConnectionCopyInfo(arg1) {
  return window['go']['main']['App']['ConnectionCopyInfo'](arg1);
}

export function ConnectionRevealPassword(arg1) {
  return window['go']['main']['App']['ConnectionRevealPassword'](arg1);
}

export function ConnectionsBatchUpdate(arg1) {
  return window['go']['main']['App']['ConnectionsBatchUpdate'](arg1);
}

export function ConnectionsCreate(arg1) {
  return window['go']['main']['App']['ConnectionsCreate'](arg1);
}

export function ConnectionsDelete(arg1) {
  return window['go']['main']['App']['ConnectionsDelete'](arg1);
}

export function ConnectionsGet(arg1) {
  return window['go']['main']['App']['ConnectionsGet'](arg1);
}

export function ConnectionsList(arg1) {
  return window['go']['main']['App']['ConnectionsList'](arg1);
}

export function ConnectionsResolve(arg1) {
  return window['go']['main']['App']['ConnectionsResolve'](arg1);
}

export function ConnectionsTouch(arg1) {
  return window['go']['main']['App']['ConnectionsTouch'](arg1);
}

export function ConnectionsUpdate(arg1) {
  return window['go']['main']['App']['ConnectionsUpdate'](arg1);
}

export function CredentialFoldersCreate(arg1, arg2) {
  return window['go']['main']['App']['CredentialFoldersCreate'](arg1, arg2);
}

export function CredentialFoldersDelete(arg1) {
  return window['go']['main']['App']['CredentialFoldersDelete'](arg1);
}

export function CredentialFoldersList() {
  return window['go']['main']['App']['CredentialFoldersList']();
}

export function CredentialFoldersUpdate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CredentialFoldersUpdate'](arg1, arg2, arg3, arg4);
}

export function CredentialsCreate(arg1) {
  return window['go']['main']['App']['CredentialsCreate'](arg1);
}

export function CredentialsDelete(arg1) {
  return window['go']['main']['App']['CredentialsDelete'](arg1);
}

export function CredentialsGet(arg1) {
  return window['go']['main']['App']['CredentialsGet'](arg1);
}

export function CredentialsHistory(arg1) {
  return window['go']['main']['App']['CredentialsHistory'](arg1);
}

export function CredentialsList() {
  return window['go']['main']['App']['CredentialsList']();
}

export function CredentialsRevealSecret(arg1) {
  return window['go']['main']['App']['CredentialsRevealSecret'](arg1);
}

export function CredentialsRotateKey(arg1) {
  return window['go']['main']['App']['CredentialsRotateKey'](arg1);
}

export function CredentialsRotatePassword(arg1, arg2) {
  return window['go']['main']['App']['CredentialsRotatePassword'](arg1, arg2);
}

export function CredentialsUpdate(arg1) {
  return window['go']['main']['App']['CredentialsUpdate'](arg1);
}

export function CredentialsUsage(arg1) {
  return window['go']['main']['App']['CredentialsUsage'](arg1);
}

export function FoldersCreate(arg1) {
  return window['go']['main']['App']['FoldersCreate'](arg1);
}

export function FoldersDelete(arg1) {
  return window['go']['main']['App']['FoldersDelete'](arg1);
}

export function FoldersGet(arg1) {
  return window['go']['main']['App']['FoldersGet'](arg1);
}

export function FoldersList() {
  return window['go']['main']['App']['FoldersList']();
}

export function FoldersUpdate(arg1) {
  return window['go']['main']['App']['FoldersUpdate'](arg1);
}

export function ForwardsActive(arg1) {
  return window['go']['main']['App']['ForwardsActive'](arg1);
}

export function ForwardsCreate(arg1) {
  return window['go']['main']['App']['ForwardsCreate'](arg1);
}

export function ForwardsDelete(arg1) {
  return window['go']['main']['App']['ForwardsDelete'](arg1);
}

export function ForwardsList(arg1) {
  return window['go']['main']['App']['ForwardsList'](arg1);
}

export function ForwardsStart(arg1, arg2) {
  return window['go']['main']['App']['ForwardsStart'](arg1, arg2);
}

export function ForwardsStop(arg1) {
  return window['go']['main']['App']['ForwardsStop'](arg1);
}

export function ForwardsUpdate(arg1) {
  return window['go']['main']['App']['ForwardsUpdate'](arg1);
}

export function GetConnectionHasPassword(arg1) {
  return window['go']['main']['App']['GetConnectionHasPassword'](arg1);
}

export function ImagesGet(arg1) {
  return window['go']['main']['App']['ImagesGet'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Ping(arg1) {
  return window['go']['main']['App']['Ping'](arg1);
}

export function RdmImport(arg1, arg2) {
  return window['go']['main']['App']['RdmImport'](arg1, arg2);
}

export function SetConnectionPassword(arg1, arg2) {
  return window['go']['main']['App']['SetConnectionPassword'](arg1, arg2);
}

export function SettingsDelete(arg1) {
  return window['go']['main']['App']['SettingsDelete'](arg1);
}

export function SettingsGet(arg1) {
  return window['go']['main']['App']['SettingsGet'](arg1);
}

export function SettingsSet(arg1, arg2) {
  return window['go']['main']['App']['SettingsSet'](arg1, arg2);
}

export function SftpCancelTransfer(arg1) {
  return window['go']['main']['App']['SftpCancelTransfer'](arg1);
}

export function SftpList(arg1, arg2) {
  return window['go']['main']['App']['SftpList'](arg1, arg2);
}

export function SftpMkdir(arg1, arg2) {
  return window['go']['main']['App']['SftpMkdir'](arg1, arg2);
}

export function SftpPickDownloadDest(arg1) {
  return window['go']['main']['App']['SftpPickDownloadDest'](arg1);
}

export function SftpPickUploadSource() {
  return window['go']['main']['App']['SftpPickUploadSource']();
}

export function SftpReadPreview(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpReadPreview'](arg1, arg2, arg3);
}

export function SftpRemove(arg1, arg2) {
  return window['go']['main']['App']['SftpRemove'](arg1, arg2);
}

export function SftpRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpRename'](arg1, arg2, arg3);
}

export function SftpStartDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpStartDownload'](arg1, arg2, arg3);
}

export function SftpStartUpload(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpStartUpload'](arg1, arg2, arg3);
}

export function SftpStat(arg1, arg2) {
  return window['go']['main']['App']['SftpStat'](arg1, arg2);
}

export function SshActiveSessions() {
  return window['go']['main']['App']['SshActiveSessions']();
}

export function SshCancelReconnect(arg1) {
  return window['go']['main']['App']['SshCancelReconnect'](arg1);
}

export function SshConnect(arg1) {
  return window['go']['main']['App']['SshConnect'](arg1);
}

export function SshDisconnect(arg1) {
  return window['go']['main']['App']['SshDisconnect'](arg1);
}

export function SshLaunchBrowser(arg1, arg2) {
  return window['go']['main']['App']['SshLaunchBrowser'](arg1, arg2);
}

export function SshResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['SshResize'](arg1, arg2, arg3);
}

export function SshRespondHostKey(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SshRespondHostKey'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SshSystemCommand(arg1) {
  return window['go']['main']['App']['SshSystemCommand'](arg1);
}

export function SshWrite(arg1, arg2) {
  return window['go']['main']['App']['SshWrite'](arg1, arg2);
}

export function VaultAutoUnlock() {
  return window['go']['main']['App']['VaultAutoUnlock']();
}

export function VaultInit(arg1, arg2) {
  return window['go']['main']['App']['VaultInit'](arg1, arg2);
}

export function VaultLock(arg1) {
  return window['go']['main']['App']['VaultLock'](arg1);
}

export function VaultStatus() {
  return window['go']['main']['App']['VaultStatus']();
}

export function VaultUnlock(arg1, arg2) {
  return window['go']['main']['App']['VaultUnlock'](arg1, arg2);
}
