// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    AuditEvent,
    Connection,
    CredentialFolder,
    CredentialHistoryEntry,
    CredentialKind,
    CredentialRef,
    CredentialSecretHistoryEntry,
    DynamicEntry,
    DynamicFolder,
    Folder,
    ImageSummary,
    InheritableSettings,
    JumpHostSpec,
    PortForward,
    ProxyBookmark,
    ResolvedSettings,
    Snippet,
    SnippetInput,
    StorageMode,
    UsageRef,
    Workspace
} from "./models.js";

import * as $models from "./models.js";

/**
 * JumpHostOverride is tagged-union with two variants: "none" (explicit
 * strip-inherited-chain) or "chain" with the full spec at .Chain.
 * 
 * JSON shape: {"kind":"none"} or {"kind":"chain", "chain": {...JumpHostSpec...}}
 * @typedef {$models.JumpHostOverride} JumpHostOverride
 */
