// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

/**
 * AuditEvent is one row of the local audit log.
 */
export class AuditEvent {
    /**
     * Creates a new AuditEvent instance.
     * @param {Partial<AuditEvent>} [$$source = {}] - The source object to create the AuditEvent.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("ts" in $$source)) {
            /**
             * unix seconds
             * @member
             * @type {number}
             */
            this["ts"] = 0;
        }
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("metadata" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuditEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AuditEvent}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField4_0($$parsedSource["metadata"]);
        }
        return new AuditEvent(/** @type {Partial<AuditEvent>} */($$parsedSource));
    }
}

/**
 * BitwardenServer is a registered Vaultwarden / Bitwarden server ssh-tool reads
 * secrets from at connect time. Neither the master password nor the API key is
 * stored here: MasterRef points at a hidden sealed vault account
 * (bitwarden:<id>:master), APIKeyRef points at the vault account behind a normal
 * API-key credential. A credential references an item via
 * config_json.bitwarden_ref {server_id, cipher_id, field}.
 */
export class BitwardenServer {
    /**
     * Creates a new BitwardenServer instance.
     * @param {Partial<BitwardenServer>} [$$source = {}] - The source object to create the BitwardenServer.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("server_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server_url"] = "";
        }
        if (!("api_key_ref" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_key_ref"] = "";
        }
        if (!("master_ref" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["master_ref"] = "";
        }
        if (!("network_profile_id" in $$source)) {
            /**
             * WireGuard profile to dial through, empty = direct
             * @member
             * @type {string}
             */
            this["network_profile_id"] = "";
        }
        if (!("last_synced_at" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["last_synced_at"] = null;
        }
        if (!("last_hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_hash"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updated_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BitwardenServer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BitwardenServer}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BitwardenServer(/** @type {Partial<BitwardenServer>} */($$parsedSource));
    }
}

/**
 * Connection is a leaf in the tree.
 */
export class Connection {
    /**
     * Creates a new Connection instance.
     * @param {Partial<Connection>} [$$source = {}] - The source object to create the Connection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("folder_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["folder_id"] = null;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("sort_order" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sort_order"] = 0;
        }
        if (!("protocol" in $$source)) {
            /**
             * Protocol selects how a connect is dialed: "ssh" (default - the
             * full SSH chain) or "local" (spawn a local PTY and run
             * InitialCommand). A local connection ignores hostname/port/auth/
             * jump; it is a saved local shell (telnet client, serial console,
             * "claude", a REPL, ...). Real column, defaulting to "ssh" so every
             * existing connection is unchanged.
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * LocalShellKind picks the shell for a "local" connection: nil / ""
             * = auto (per-platform default), else one of the kinds resolveShell
             * accepts ("bash"/"zsh"/"sh"/"powershell"/"cmd"/"wsl"). Ignored for
             * SSH connections.
             * @member
             * @type {string | null | undefined}
             */
            this["local_shell_kind"] = undefined;
        }
        if (!("overrides" in $$source)) {
            /**
             * @member
             * @type {InheritableSettings}
             */
            this["overrides"] = (new InheritableSettings());
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("favorite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["favorite"] = false;
        }
        if (!("sensitive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sensitive"] = false;
        }
        if (!("icon_image_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["icon_image_id"] = null;
        }
        if (!("icon_name" in $$source)) {
            /**
             * IconName / IconColor: built-in lucide icon + palette colour, same
             * semantics as on Folder. Mutually exclusive with IconImageID.
             * @member
             * @type {string | null}
             */
            this["icon_name"] = null;
        }
        if (!("icon_color" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["icon_color"] = null;
        }
        if (!("last_used_at" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["last_used_at"] = null;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updated_at"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["password_vault_key"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * VncPasswordVaultKey points at the vault entry holding this
             * connection's VNC (RFB) password, when set. Same lifecycle as
             * PasswordVaultKey - a real column, not part of overrides_json,
             * because the secret itself lives in the vault and only the key is
             * stored here. nil means "no stored VNC password" (noVNC prompts if
             * the server demands auth).
             * @member
             * @type {string | null | undefined}
             */
            this["vnc_password_vault_key"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Connection}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("overrides" in $$parsedSource) {
            $$parsedSource["overrides"] = $$createField7_0($$parsedSource["overrides"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField8_0($$parsedSource["tags"]);
        }
        return new Connection(/** @type {Partial<Connection>} */($$parsedSource));
    }
}

/**
 * CredentialFolder groups credentials (mirrors connection Folder).
 */
export class CredentialFolder {
    /**
     * Creates a new CredentialFolder instance.
     * @param {Partial<CredentialFolder>} [$$source = {}] - The source object to create the CredentialFolder.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("parent_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["parent_id"] = null;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("sort_order" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sort_order"] = 0;
        }
        if (!("icon_name" in $$source)) {
            /**
             * Built-in (lucide) icon + palette colour. Credential folders never
             * had an uploaded-image icon, so these are the only icon fields.
             * @member
             * @type {string | null}
             */
            this["icon_name"] = null;
        }
        if (!("icon_color" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["icon_color"] = null;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updated_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialFolder instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CredentialFolder}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialFolder(/** @type {Partial<CredentialFolder>} */($$parsedSource));
    }
}

/**
 * CredentialHistoryEntry is a metadata-only audit record (or pointer to a
 * retained-history entry in the vault).
 */
export class CredentialHistoryEntry {
    /**
     * Creates a new CredentialHistoryEntry instance.
     * @param {Partial<CredentialHistoryEntry>} [$$source = {}] - The source object to create the CredentialHistoryEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("credential_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["credential_id"] = "";
        }
        if (!("changed_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["changed_at"] = 0;
        }
        if (!("note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["note"] = "";
        }
        if (!("rotated_by" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rotated_by"] = "";
        }
        if (!("has_value" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_value"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialHistoryEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CredentialHistoryEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialHistoryEntry(/** @type {Partial<CredentialHistoryEntry>} */($$parsedSource));
    }
}

/**
 * CredentialKind / StorageMode mirror the Rust enums.
 * @readonly
 * @enum {string}
 */
export const CredentialKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    CredPassword: "password",
    CredKey: "key",
    CredAgent: "agent",
    CredOpkssh: "opkssh",
    CredVault: "vault",

    /**
     * CredAPIToken stores an opaque token paired with an identifier
     * (e.g. proxmox `user@realm!tokenid` + secret). Not usable for
     * SSH auth - referenced by external integrations like the dynamic
     * inventory providers.
     */
    CredAPIToken: "api_token",
};

/**
 * CredentialRef holds metadata only. Secrets live in vault under VaultKey.
 */
export class CredentialRef {
    /**
     * Creates a new CredentialRef instance.
     * @param {Partial<CredentialRef>} [$$source = {}] - The source object to create the CredentialRef.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("folder_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["folder_id"] = null;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {CredentialKind}
             */
            this["kind"] = CredentialKind.$zero;
        }
        if (!("storage_mode" in $$source)) {
            /**
             * @member
             * @type {StorageMode}
             */
            this["storage_mode"] = StorageMode.$zero;
        }
        if (!("hint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hint"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("config" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["config"] = {};
        }
        if (!("public_key" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["public_key"] = null;
        }
        if (!("vault_key" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["vault_key"] = null;
        }
        if (!("default_username" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["default_username"] = null;
        }
        if (!("last_rotated_at" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["last_rotated_at"] = null;
        }
        if (!("expires_at" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["expires_at"] = null;
        }
        if (!("rotation_reminder_days" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["rotation_reminder_days"] = null;
        }
        if (!("retain_history" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["retain_history"] = false;
        }
        if (!("icon_image_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["icon_image_id"] = null;
        }
        if (!("icon_name" in $$source)) {
            /**
             * IconName / IconColor: built-in lucide icon + palette colour, same
             * semantics as on Connection. Mutually exclusive with IconImageID.
             * @member
             * @type {string | null}
             */
            this["icon_name"] = null;
        }
        if (!("icon_color" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["icon_color"] = null;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updated_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialRef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CredentialRef}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField6_0($$parsedSource["tags"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField7_0($$parsedSource["config"]);
        }
        return new CredentialRef(/** @type {Partial<CredentialRef>} */($$parsedSource));
    }
}

/**
 * CredentialSecretHistoryEntry is one snapshot of a previous secret
 * value, sealed in the file vault under VaultAccount. The plaintext
 * is never returned by ListSecretHistory - callers fetch it on
 * demand via RevealSecretHistory (which also resets the clipboard
 * auto-clear timer, same as a live reveal).
 */
export class CredentialSecretHistoryEntry {
    /**
     * Creates a new CredentialSecretHistoryEntry instance.
     * @param {Partial<CredentialSecretHistoryEntry>} [$$source = {}] - The source object to create the CredentialSecretHistoryEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("credential_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["credential_id"] = "";
        }
        if (!("rotated_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rotated_at"] = 0;
        }
        if (!("vault_account" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vault_account"] = "";
        }
        if (!("note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["note"] = "";
        }
        if (!("rotated_by" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rotated_by"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialSecretHistoryEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CredentialSecretHistoryEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialSecretHistoryEntry(/** @type {Partial<CredentialSecretHistoryEntry>} */($$parsedSource));
    }
}

/**
 * DynamicEntry is a single cached child of a dynamic folder. Created
 * by the refresh path, never edited by the user.
 */
export class DynamicEntry {
    /**
     * Creates a new DynamicEntry instance.
     * @param {Partial<DynamicEntry>} [$$source = {}] - The source object to create the DynamicEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("folder_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folder_id"] = "";
        }
        if (!("external_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["external_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("raw" in $$source)) {
            /**
             * @member
             * @type {json$0.RawMessage}
             */
            this["raw"] = null;
        }
        if (!("sort_order" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sort_order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DynamicEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DynamicEntry}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField7_0($$parsedSource["tags"]);
        }
        return new DynamicEntry(/** @type {Partial<DynamicEntry>} */($$parsedSource));
    }
}

/**
 * DynamicFolder is the side-table row for a folder driven by an
 * external provider. The base row in `folders` carries the inherit
 * settings (port, username, jump host, credential); this struct only
 * adds the provider plumbing.
 */
export class DynamicFolder {
    /**
     * Creates a new DynamicFolder instance.
     * @param {Partial<DynamicFolder>} [$$source = {}] - The source object to create the DynamicFolder.
     */
    constructor($$source = {}) {
        if (!("folder_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folder_id"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("config" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["config"] = {};
        }
        if (!("refresh_seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["refresh_seconds"] = 0;
        }
        if (!("last_pulled_at" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["last_pulled_at"] = null;
        }
        if (!("last_error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DynamicFolder instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DynamicFolder}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField2_0($$parsedSource["config"]);
        }
        return new DynamicFolder(/** @type {Partial<DynamicFolder>} */($$parsedSource));
    }
}

/**
 * Folder is a node in the connection tree. ParentID == nil means root.
 */
export class Folder {
    /**
     * Creates a new Folder instance.
     * @param {Partial<Folder>} [$$source = {}] - The source object to create the Folder.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("parent_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["parent_id"] = null;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("sort_order" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sort_order"] = 0;
        }
        if (!("settings" in $$source)) {
            /**
             * @member
             * @type {InheritableSettings}
             */
            this["settings"] = (new InheritableSettings());
        }
        if (!("icon_image_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["icon_image_id"] = null;
        }
        if (!("icon_name" in $$source)) {
            /**
             * IconName is a built-in (lucide) icon key; IconColor is a palette
             * name (see frontend palette.ts) tinting it. Mutually exclusive with
             * IconImageID - setting one clears the other. Both nil = default icon.
             * @member
             * @type {string | null}
             */
            this["icon_name"] = null;
        }
        if (!("icon_color" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["icon_color"] = null;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updated_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Folder instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Folder}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField4_0($$parsedSource["settings"]);
        }
        return new Folder(/** @type {Partial<Folder>} */($$parsedSource));
    }
}

/**
 * ListImageIDs returns every image id in the store paired with a
 * usage count (how many folders + connections reference it). Used
 * by the icon picker so the user can pick from images already in
 * the DB (e.g. RDM-imported logos) instead of re-uploading them.
 */
export class ImageSummary {
    /**
     * Creates a new ImageSummary instance.
     * @param {Partial<ImageSummary>} [$$source = {}] - The source object to create the ImageSummary.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("mime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mime"] = "";
        }
        if (!("use_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["use_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImageSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImageSummary(/** @type {Partial<ImageSummary>} */($$parsedSource));
    }
}

/**
 * InfisicalServer is a registered Infisical instance ssh-tool reads secrets from
 * at connect time (the per-request sibling of bitwarden_servers). There is no
 * master password - Infisical decrypts server-side, so the only secret is the
 * machine-identity API key, held behind a normal api_token credential pointed at
 * by APIKeyRef. A credential references a secret via
 * config_json.infisical_ref {server_id, project_id, environment, secret_path, key}.
 */
export class InfisicalServer {
    /**
     * Creates a new InfisicalServer instance.
     * @param {Partial<InfisicalServer>} [$$source = {}] - The source object to create the InfisicalServer.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("server_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server_url"] = "";
        }
        if (!("api_key_ref" in $$source)) {
            /**
             * credential id (api_token) holding client_id/secret
             * @member
             * @type {string}
             */
            this["api_key_ref"] = "";
        }
        if (!("network_profile_id" in $$source)) {
            /**
             * WireGuard profile to dial through, empty = direct
             * @member
             * @type {string}
             */
            this["network_profile_id"] = "";
        }
        if (!("last_used_at" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["last_used_at"] = null;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updated_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InfisicalServer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InfisicalServer}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InfisicalServer(/** @type {Partial<InfisicalServer>} */($$parsedSource));
    }
}

/**
 * InheritableSettings: every field is a pointer (or empty map / nil pointer
 * helper struct) so we can distinguish "unset, inherit from parent" from
 * "explicitly set to zero value".
 * 
 * JumpHost uses the JumpHostOverride wrapper because there's a meaningful
 * "explicit no-jump" case that's distinct from "inherit".
 */
export class InheritableSettings {
    /**
     * Creates a new InheritableSettings instance.
     * @param {Partial<InheritableSettings>} [$$source = {}] - The source object to create the InheritableSettings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["username"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["auth_ref"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {JumpHostOverride | null | undefined}
             */
            this["jump_host"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["ssh_options"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["env_vars"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["color_tag"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["broadcast_group_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["keepalive_interval"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["terminal_type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * InitialCommand is run in the shell right after connect (e.g.
             * "cd /var/www", "tmux new -A -s main"). nil means inherit from
             * folder ancestry; "" means explicitly none (breaks an inherited
             * command). Sent to the TARGET hop's PTY only, with a trailing
             * newline, so it runs and lands in the user's own scrollback.
             * @member
             * @type {string | null | undefined}
             */
            this["initial_command"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * AutoReconnect: when true, sessions that drop without a user
             * Disconnect trigger an exponential-backoff reconnect loop (capped).
             * nil means "inherit from folder ancestry"; false means "explicitly
             * don't reconnect even if the parent folder says yes".
             * @member
             * @type {boolean | null | undefined}
             */
            this["auto_reconnect"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Verbose: when true, the SSH layer emits diagnostic events
             * (resolved settings, TCP dial, handshake, auth attempts) to the
             * frontend so the user can see why a connect attempt fails. Same
             * tri-state inheritance as AutoReconnect.
             * @member
             * @type {boolean | null | undefined}
             */
            this["verbose"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * VncEnabled gates the "Open VNC console" action on a connection.
             * Most SSH hosts have no VNC server, so the console is opt-in: the
             * action and the editor's VNC fields only show when this resolves
             * true. Tri-state inheritance so a folder of desktops can enable it
             * for all children.
             * @member
             * @type {boolean | null | undefined}
             */
            this["vnc_enabled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * VncPort is the RFB port for the "Open VNC console" action on a
             * generic (non-Proxmox) connection. nil means inherit; when unset
             * all the way up the chain the open path defaults to 5900.
             * @member
             * @type {number | null | undefined}
             */
            this["vnc_port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * VncUseTunnel: when true, the VNC console dials the RFB port
             * through the connection's SSH session (so vnc_port is reached on
             * the remote's loopback, like a localhost-bound x11vnc). When false
             * the bridge dials host:vnc_port directly. Tri-state inheritance.
             * @member
             * @type {boolean | null | undefined}
             */
            this["vnc_use_tunnel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * NetworkProfileID routes the FIRST SSH hop through a userspace
             * WireGuard tunnel (internal/wg). nil = inherit from ancestry;
             * "" = explicitly direct (breaks an inherited profile); otherwise
             * the id of a network_profiles row. Jump-chain hops after the
             * first ride the previous hop's SSH channel and need no network
             * of their own.
             * @member
             * @type {string | null | undefined}
             */
            this["network_profile_id"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InheritableSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InheritableSettings}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ssh_options" in $$parsedSource) {
            $$parsedSource["ssh_options"] = $$createField4_0($$parsedSource["ssh_options"]);
        }
        if ("env_vars" in $$parsedSource) {
            $$parsedSource["env_vars"] = $$createField5_0($$parsedSource["env_vars"]);
        }
        return new InheritableSettings(/** @type {Partial<InheritableSettings>} */($$parsedSource));
    }
}

/**
 * JumpHostOverride is tagged-union with two variants: "none" (explicit
 * strip-inherited-chain) or "chain" with the full spec at .Chain.
 * 
 * JSON shape: {"kind":"none"} or {"kind":"chain", "chain": {...JumpHostSpec...}}
 * @typedef {any} JumpHostOverride
 */

/**
 * JumpHostSpec describes one hop. Recursive via.
 */
export class JumpHostSpec {
    /**
     * Creates a new JumpHostSpec instance.
     * @param {Partial<JumpHostSpec>} [$$source = {}] - The source object to create the JumpHostSpec.
     */
    constructor($$source = {}) {
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["username"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["auth_ref"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {JumpHostSpec | null | undefined}
             */
            this["via"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JumpHostSpec instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JumpHostSpec}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("via" in $$parsedSource) {
            $$parsedSource["via"] = $$createField4_0($$parsedSource["via"]);
        }
        return new JumpHostSpec(/** @type {Partial<JumpHostSpec>} */($$parsedSource));
    }
}

/**
 * KeepassDatabase is a registered .kdbx ssh-tool reads secrets from. The master
 * password and key file are NOT stored here - MasterRef / KeyfileRef point at
 * vault accounts. For remote sources the file is fetched and cached under
 * DataDir; Path then points at the cache and URL at the origin.
 */
export class KeepassDatabase {
    /**
     * Creates a new KeepassDatabase instance.
     * @param {Partial<KeepassDatabase>} [$$source = {}] - The source object to create the KeepassDatabase.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {KeepassSource}
             */
            this["source"] = KeepassSource.$zero;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("master_ref" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["master_ref"] = "";
        }
        if (!("keyfile_ref" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyfile_ref"] = "";
        }
        if (!("remote_config" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["remote_config"] = {};
        }
        if (!("last_fetched_at" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["last_fetched_at"] = null;
        }
        if (!("last_etag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_etag"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updated_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeepassDatabase instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KeepassDatabase}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("remote_config" in $$parsedSource) {
            $$parsedSource["remote_config"] = $$createField7_0($$parsedSource["remote_config"]);
        }
        return new KeepassDatabase(/** @type {Partial<KeepassDatabase>} */($$parsedSource));
    }
}

/**
 * KeepassSource is where a KeePass database file lives.
 * @readonly
 * @enum {string}
 */
export const KeepassSource = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    KeepassLocal: "local",
    KeepassWebDAV: "webdav",
    KeepassSFTP: "sftp",
};

/**
 * PortForward is the persisted spec of a forward (not its running state).
 * Auto-start ones get instantiated whenever the parent connection connects.
 */
export class PortForward {
    /**
     * Creates a new PortForward instance.
     * @param {Partial<PortForward>} [$$source = {}] - The source object to create the PortForward.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_id"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * local|remote|dynamic
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("local_addr" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["local_addr"] = null;
        }
        if (!("local_port" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["local_port"] = null;
        }
        if (!("remote_host" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["remote_host"] = null;
        }
        if (!("remote_port" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["remote_port"] = null;
        }
        if (!("auto_start" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_start"] = false;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("bookmarks" in $$source)) {
            /**
             * @member
             * @type {ProxyBookmark[]}
             */
            this["bookmarks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortForward instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PortForward}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bookmarks" in $$parsedSource) {
            $$parsedSource["bookmarks"] = $$createField9_0($$parsedSource["bookmarks"]);
        }
        return new PortForward(/** @type {Partial<PortForward>} */($$parsedSource));
    }
}

/**
 * ProxyBookmark is a named URL shortcut stored on a dynamic (SOCKS5) forward.
 */
export class ProxyBookmark {
    /**
     * Creates a new ProxyBookmark instance.
     * @param {Partial<ProxyBookmark>} [$$source = {}] - The source object to create the ProxyBookmark.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyBookmark instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyBookmark}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyBookmark(/** @type {Partial<ProxyBookmark>} */($$parsedSource));
    }
}

/**
 * ResolvedSettings is the merged result the SSH layer consumes.
 */
export class ResolvedSettings {
    /**
     * Creates a new ResolvedSettings instance.
     * @param {Partial<ResolvedSettings>} [$$source = {}] - The source object to create the ResolvedSettings.
     */
    constructor($$source = {}) {
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["username"] = null;
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("auth_ref" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["auth_ref"] = null;
        }
        if (!("jump_host" in $$source)) {
            /**
             * @member
             * @type {JumpHostSpec | null}
             */
            this["jump_host"] = null;
        }
        if (!("ssh_options" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["ssh_options"] = {};
        }
        if (!("env_vars" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["env_vars"] = {};
        }
        if (!("color_tag" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["color_tag"] = null;
        }
        if (!("broadcast_group_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["broadcast_group_id"] = null;
        }
        if (!("keepalive_interval" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["keepalive_interval"] = 0;
        }
        if (!("terminal_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["terminal_type"] = "";
        }
        if (!("initial_command" in $$source)) {
            /**
             * InitialCommand is run in the shell right after connect ("" = none).
             * @member
             * @type {string}
             */
            this["initial_command"] = "";
        }
        if (!("auto_reconnect" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_reconnect"] = false;
        }
        if (!("verbose" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["verbose"] = false;
        }
        if (!("vnc_enabled" in $$source)) {
            /**
             * VncPort is the resolved RFB port for the VNC console action,
             * defaulting to 5900 when unset anywhere in the chain. VncUseTunnel
             * says whether to reach it through the connection's SSH session.
             * @member
             * @type {boolean}
             */
            this["vnc_enabled"] = false;
        }
        if (!("vnc_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["vnc_port"] = 0;
        }
        if (!("vnc_use_tunnel" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["vnc_use_tunnel"] = false;
        }
        if (!("network_profile_id" in $$source)) {
            /**
             * NetworkProfileID: non-nil when the first hop should dial through
             * the userspace WireGuard tunnel of this network profile. An
             * explicit "" override normalizes to nil here.
             * @member
             * @type {string | null}
             */
            this["network_profile_id"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolvedSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResolvedSettings}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("jump_host" in $$parsedSource) {
            $$parsedSource["jump_host"] = $$createField4_0($$parsedSource["jump_host"]);
        }
        if ("ssh_options" in $$parsedSource) {
            $$parsedSource["ssh_options"] = $$createField5_0($$parsedSource["ssh_options"]);
        }
        if ("env_vars" in $$parsedSource) {
            $$parsedSource["env_vars"] = $$createField6_0($$parsedSource["env_vars"]);
        }
        return new ResolvedSettings(/** @type {Partial<ResolvedSettings>} */($$parsedSource));
    }
}

/**
 * Snippet is a short reusable command body the user fires into an
 * active terminal. Global by default (ConnectionID nil); set
 * ConnectionID to scope a snippet to a single connection.
 */
export class Snippet {
    /**
     * Creates a new Snippet instance.
     * @param {Partial<Snippet>} [$$source = {}] - The source object to create the Snippet.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["connection_id"] = undefined;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("use_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["use_count"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["last_used_at"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updated_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snippet instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snippet}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new Snippet(/** @type {Partial<Snippet>} */($$parsedSource));
    }
}

/**
 * SnippetInput is what the frontend sends for create / update.
 */
export class SnippetInput {
    /**
     * Creates a new SnippetInput instance.
     * @param {Partial<SnippetInput>} [$$source = {}] - The source object to create the SnippetInput.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["connection_id"] = undefined;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnippetInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SnippetInput}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        return new SnippetInput(/** @type {Partial<SnippetInput>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const StorageMode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StorageManaged: "managed",
    StorageFileRef: "file_ref",
    StorageExternal: "external",
};

/**
 * UsageRef is a reverse-lookup hit: a folder or connection that references
 * the given credential anywhere in its settings (auth_ref or jump chain).
 */
export class UsageRef {
    /**
     * Creates a new UsageRef instance.
     * @param {Partial<UsageRef>} [$$source = {}] - The source object to create the UsageRef.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * "folder" | "connection"
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hostname"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageRef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UsageRef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageRef(/** @type {Partial<UsageRef>} */($$parsedSource));
    }
}

/**
 * Workspace is a named snapshot of tabs + their layout + group metadata.
 * LayoutJSON is opaque to the store layer - the frontend writes a
 * shape it knows how to read on restore. We just persist the blob.
 */
export class Workspace {
    /**
     * Creates a new Workspace instance.
     * @param {Partial<Workspace>} [$$source = {}] - The source object to create the Workspace.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("layout_json" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["layout_json"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["last_opened_at"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updated_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Workspace instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Workspace}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Workspace(/** @type {Partial<Workspace>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = InheritableSettings.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = JumpHostSpec.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = ProxyBookmark.createFrom;
const $$createType7 = $Create.Array($$createType6);
